[package]
name = "trust"
version = "0.1.0"
authors = ["Jorge Luis Pérez <jorge.perez@almundo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tun-tap = "0.1.2"
endianness = "0.2"
etherparse = "0.8.3"